# Generated by Django 5.2.17 on 2026-09-16 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAnnouncement',
            fields=[
                ('announcement_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(default='All', max_length=50)),
                ('priority', models.CharField(default='high', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('book_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('isbn', models.CharField(blank=True, default='', max_length=50)),
                ('module_code', models.CharField(default='IT301', max_length=20)),
                ('holding_campus', models.CharField(default='Midrand Campus', max_length=100)),
                ('total_copies', models.IntegerField(default=5)),
                ('available_copies', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('log_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content_type', models.CharField(default='post', max_length=50)),
                ('content_snippet', models.TextField()),
                ('toxicity_score', models.FloatField(default=0.0)),
                ('action_taken', models.CharField(default='approved', max_length=30)),
                ('reviewed_by', models.CharField(default='AI Safety Guard', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='student', max_length=30)),
                ('campus', models.CharField(default='Midrand Campus', max_length=100)),
                ('qualification', models.CharField(default='IT', max_length=50)),
                ('academic_year', models.CharField(default='3rd Year', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('is_mentor', models.BooleanField(default=False)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('domain', models.CharField(default='Software Engineering', max_length=100)),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('scheduled_time', models.CharField(default='Today at 14:00', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to='core.userprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFoundItem',
            fields=[
                ('item_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Electronics', max_length=100)),
                ('campus_location', models.CharField(default='Sandton Campus Lab 4', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='found_unclaimed', max_length=40)),
                ('held_at_security_desk', models.BooleanField(default=True)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('job_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(default='Sandton, Gauteng', max_length=150)),
                ('campus_target', models.CharField(default='All Campuses', max_length=150)),
                ('job_type', models.CharField(default='Graduate Programme', max_length=50)),
                ('qualification', models.CharField(default='IT', max_length=50)),
                ('stipend_or_salary', models.CharField(default='R18,000 / month', max_length=100)),
                ('deadline', models.CharField(default='30 Oct 2026', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='approved', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(default='under_review', max_length=30)),
                ('resume_url', models.CharField(blank=True, default='', max_length=500)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobopportunity')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CampusPost',
            fields=[
                ('post_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('cohort', models.CharField(default='BSc IT 3rd Year', max_length=100)),
                ('likes_count', models.IntegerField(default=0)),
                ('moderation_status', models.CharField(default='approved', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BookTransferRequest',
            fields=[
                ('transfer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('from_campus', models.CharField(max_length=100)),
                ('to_campus', models.CharField(max_length=100)),
                ('status', models.CharField(default='in_transit', max_length=30)),
                ('courier_tracking_number', models.CharField(blank=True, default='', max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.librarybook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_transfers', to='core.userprofile')),
            ],
        ),
    ]
