# Generated by Django 5.2.17 on 2026-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusannouncement',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campusannouncement',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='elevator_pitch_video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='has_elevator_pitch',
            field=models.BooleanField(default=True),
        ),
    ]
